[project]
name = "energy-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.4",
    "matplotlib>=3.10.8",
    "requests>=2.32.5",
    "poethepoet>=0.38.0",
    "polars>=1.37.1",
    "jupyter>=1.1.1",  # For drax_export_histograms.py - to remove
    "pandas>=2.3.3",  # For drax_export_histograms.py - to remove
]
[tool.poe.tasks]
edit = "marimo edit notebooks"
run = "server.py"
